version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8001
      - REACT_APP_WEBSOCKET_URL=ws://localhost:8001
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/app
    environment:
      - ENVIRONMENT=development
      - MONGO_URL=mongodb://mongo:27017/cultural_center
      - SECRET_KEY=dev-secret-key
      - DEBUG=True
    depends_on:
      - mongo
    command: uvicorn server:app --host 0.0.0.0 --port 8001 --reload

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=cultural_center

volumes:
  mongo_data: